version: "3.3"
# snipe-it導入用コンポーザ
services:
  snipeit:
    image: snipe/snipe-it
    env_file: .env
    networks:
      db_net:
        ipv4_address: 172.18.1.8
    ports:
      - target: 80
        published: 58080
        protocol: tcp
        mode: host
    depends_on:
      - db
  db:
    image: mariadb:10.1
    env_file: .env
    networks:
      db_net:
        ipv4_address: 172.18.1.9
    ports:
        - target: 3306
          published: 3306
          protocol: tcp
          mode: host
    restart: on-failure:1
networks:
  db_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/24