version: "3.3"
# snipe-it導入用コンポーザ
services:
  snipeit:
    image: snipe/snipe-it:v4.1.13
    env_file: .env
    ports:
      - target: 80
        published: 58080
        protocol: tcp
        mode: host
    depends_on:
      - db
    links:
      - db
  db:
    build:
      context: ./db
      dockerfile: db.dockerfile
    env_file: .env
#    volumes:
#      - type: volume
#        source: dbdata
#        target: /var/lib/mysql
    restart: on-failure:1
#volumes:
#  webdata:
#    external: true
#  dbdata:
#    external: true