---
- name: Install Apache
  apt: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apache2
    - apache2-utils


- name: Enable modules
  command: a2enmod "{{ item }}"
  with_items:
    - ssl

- name: stop apache
  service: 
    name: apache2
    state: stopped

- name: config apache
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 000-default.j2, dest: /etc/apache2/sites-available/000-default.conf }
    - { src: default-ssl.j2, dest:  /etc/apache2/sites-available/default-ssl.conf }

- name: symlink config
  file:
    src: "/etc/apache2/sites-available/{{ item }}"
    dest: "/etc/apache2/sites-enabled/{{ item }}"
    state: link
  with_items:
    - 000-default.conf
    - default-ssl.conf

- name: copy security config
  template:
    src: security.conf
    dest: /etc/apache2/conf-available/security.conf

- name: copy blank html
  template:
    src: index.j2
    dest: /var/www/html/index.html

- name: Start Apache
  service: name=apache2 state=restarted
