---
- name: Install Apache
  apt: name={{item}} state=present
  with_items:
    - apache2
    - apache2-utils

- name: Enable modules
  command: a2enmod {{item}}
  with_items:
    - ssl

- name: Stop Apache
  service: name=apache2 state=stopped

- name: Configure Apache
  template: src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: 000-default.j2, dest: /etc/apache2/sites-available/000-default.conf }
    - { src: default-ssl.j2, dest:  /etc/apache2/sites-available/default-ssl.conf }
  file:
    src: '/etc/apache2/sites-available/{{ item.src }}'
    dest: '/etc/apache2/sites-enabled/{{ item.dest }}'
    state: link
  with_items:
    - { src: '000-default.j2' , '000-default.conf' }
    - { src: 'default-ssl.j2' , 'default-ssl.conf' }

- name: Start Apache
  service: name=apache2 state=started